# - ros_topic_name: "/X3/gazebo/command/motor_speed"
#   gz_topic_name: "/X3/gazebo/command/motor_speed"
#   ros_type_name: "actuator_msgs/msg/Actuators"
#   gz_type_name: "gz.msgs.Actuators"
#   direction: "ROS_TO_GZ"
- ros_topic_name: "/X3/camera"
  gz_topic_name: "/X3/camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"